FROM node:18-alpine

WORKDIR /app

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli

# Exponer puerto de desarrollo
EXPOSE 4200

# El comando se configura en docker-compose.yml
CMD ["sh"]
