version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-hiddengem}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/hiddengem}"
      SECRET_KEY: "${SECRET_KEY:-please_change_me_in_production}"
      RAWG_API_KEY: "${RAWG_API_KEY}"
      ENVIRONMENT: "${ENVIRONMENT:-production}"
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data: