FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install scrapy

# Copiar el código del proyecto
COPY . .

# Variables de entorno para la base de datos y otros ajustes
ENV PYTHONPATH=/app
ENV MAX_GAMES=5000

# Comando para ejecutar el scraper
CMD ["python", "-m", "app.scripts.run_scraper", "--now", "--max-games", "${MAX_GAMES}"]
